#!/bin/bash

(which npm || which fonttools) && read -pr "Please enter the shell command to install NPM and Fonttools: " install_command

[[ $install_command ]] && $install_command

rm -rf iosevka
git submodule update --init --depth 1

rm -rf setup