[buildPlans.bunni]
family = "bunni"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.bunni.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-touching-serifless"
a = "double-storey-serifless"
b = "toothless-corner"
c = "serifless"
d = "toothless-corner-serifless"
f = "flat-hook-crossbar-at-x-height"
g = "single-storey-serifless"
i = "hooky"
j = "flat-hook-serifed"
k = "curly-serifless"
l = "serifed-asymmetric"
m = "normal"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner"
r = "serifless"
s = "serifless"
t = "standard-short-neck"
u = "toothless-corner"
v = "curly"
x = "curly-serifless"
y = "straight"
long-s = "flat-hook"
eszet = "longs-s-lig"
lower-alpha = "tailed-barred"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
lower-xi = "rounded"
cyrl-capital-ka = "straight-serifless"
cyrl-ka = "straight-serifless"
cyrl-capital-u = "straight-turn"
one = "no-base"
two = "curly-neck"
three = "two-arcs"
four = "semi-open-non-crossing"
five = "vertical-upper-left-bar"
six = "open-contour"
seven = "bend-serifless"
eight = "crossing"
nine = "open-contour"
asterisk = "turn-hex-low"
underscore = "high"
pilcrow = "low"
caret = "low"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
ampersand = "et-toothless-corner"
at = "fourfold"
dollar = "interrupted-cap"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
bar = "force-upright"
lig-ltgteq = "slanted"
question = "smooth"
punctuation-dot = "round"
diacritic-dot = "round"

[buildPlans.bunni.variants.italic]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-touching-serifless"
a = "single-storey-serifless"
b = "toothless-corner"
c = "serifless"
d = "toothless-corner-serifless"
e = "rounded"
f = "flat-hook-diagonal-tailed-crossbar-at-x-height"
g = "single-storey-serifless"
h = "straight"
i = "tailed-serifed"
j = "diagonal-tailed-serifed"
k = "diagonal-tailed-cursive-serifless"
l = "diagonal-tailed"
m = "tailed"
n = "straight"
q = "earless-corner-diagonal-tailed"
s = "bilateral-inward-serifed"
t = "standard-short-neck"
u = "toothless-rounded-motion-serifed"
v = "curly"
w = "straight"
y = "straight-turn"
z = "curly-serifless"
five = "oblique-upper-left-bar"
seven = "curly-serifed"
lower-lambda = "straight-turn"
punctuation-dot = "round"
diacritic-dot = "round"

[buildPlans.bunni.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.bunni.metric-override]
powerlineScaleX = 1
powerlineScaleY = 1

[buildPlans.bunni.ligations]
inherits = "dlig"

[buildPlans.bunnit]
family = "bunnit"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.bunnit.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-touching-serifless"
a = "double-storey-serifless"
b = "toothless-corner"
c = "serifless"
d = "toothless-corner-serifless"
f = "flat-hook-crossbar-at-x-height"
g = "single-storey-serifless"
i = "hooky"
j = "flat-hook-serifed"
k = "curly-serifless"
l = "serifed-asymmetric"
m = "normal"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner"
r = "serifless"
s = "serifless"
t = "standard-short-neck"
u = "toothless-corner"
v = "curly"
x = "curly-serifless"
y = "straight"
long-s = "flat-hook"
eszet = "longs-s-lig"
lower-alpha = "tailed-barred"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
lower-xi = "rounded"
cyrl-capital-ka = "straight-serifless"
cyrl-ka = "straight-serifless"
cyrl-capital-u = "straight-turn"
one = "no-base"
two = "curly-neck"
three = "two-arcs"
four = "semi-open-non-crossing"
five = "vertical-upper-left-bar"
six = "open-contour"
seven = "bend-serifless"
eight = "crossing"
nine = "open-contour"
asterisk = "turn-hex-low"
underscore = "high"
pilcrow = "low"
caret = "low"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
ampersand = "et-toothless-corner"
at = "fourfold"
dollar = "interrupted-cap"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
bar = "force-upright"
lig-ltgteq = "slanted"
question = "smooth"
punctuation-dot = "round"
diacritic-dot = "round"

[buildPlans.bunnit.variants.italic]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-touching-serifless"
a = "single-storey-serifless"
b = "toothless-corner"
c = "serifless"
d = "toothless-corner-serifless"
e = "rounded"
f = "flat-hook-diagonal-tailed-crossbar-at-x-height"
g = "single-storey-serifless"
h = "straight"
i = "tailed-serifed"
j = "diagonal-tailed-serifed"
k = "diagonal-tailed-cursive-serifless"
l = "diagonal-tailed"
m = "tailed"
n = "straight"
q = "earless-corner-diagonal-tailed"
s = "bilateral-inward-serifed"
t = "standard-short-neck"
u = "toothless-rounded-motion-serifed"
v = "curly"
w = "straight"
y = "straight-turn"
z = "curly-serifless"
five = "oblique-upper-left-bar"
seven = "curly-serifed"
lower-lambda = "straight-turn"
punctuation-dot = "round"
diacritic-dot = "round"

[buildPlans.bunnit.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.bunnit.metric-override]
powerlineScaleX = 1
powerlineScaleY = 1

[buildPlans.bunnit.ligations]
inherits = "dlig"

[buildPlans.bunniq]
family = "bunniq"
spacing = "quasi-proportional-extension-only"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.bunniq.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-touching-serifless"
a = "double-storey-serifless"
b = "toothless-corner"
c = "serifless"
d = "toothless-corner-serifless"
f = "flat-hook-crossbar-at-x-height"
g = "single-storey-serifless"
i = "hooky"
j = "flat-hook-serifed"
k = "curly-serifless"
l = "serifed-asymmetric"
m = "normal"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner"
r = "serifless"
s = "serifless"
t = "standard-short-neck"
u = "toothless-corner"
v = "curly"
x = "curly-serifless"
y = "straight"
long-s = "flat-hook"
eszet = "longs-s-lig"
lower-alpha = "tailed-barred"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
lower-xi = "rounded"
cyrl-capital-ka = "straight-serifless"
cyrl-ka = "straight-serifless"
cyrl-capital-u = "straight-turn"
one = "no-base"
two = "curly-neck"
three = "two-arcs"
four = "semi-open-non-crossing"
five = "vertical-upper-left-bar"
six = "open-contour"
seven = "bend-serifless"
eight = "crossing"
nine = "open-contour"
asterisk = "turn-hex-low"
underscore = "high"
pilcrow = "low"
caret = "low"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
ampersand = "et-toothless-corner"
at = "fourfold"
dollar = "interrupted-cap"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
bar = "force-upright"
lig-ltgteq = "slanted"
question = "smooth"
punctuation-dot = "round"
diacritic-dot = "round"

[buildPlans.bunniq.variants.italic]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-touching-serifless"
a = "single-storey-serifless"
b = "toothless-corner"
c = "serifless"
d = "toothless-corner-serifless"
e = "rounded"
f = "flat-hook-diagonal-tailed-crossbar-at-x-height"
g = "single-storey-serifless"
h = "straight"
i = "tailed-serifed"
j = "diagonal-tailed-serifed"
k = "diagonal-tailed-cursive-serifless"
l = "diagonal-tailed"
m = "tailed"
n = "straight"
q = "earless-corner-diagonal-tailed"
s = "bilateral-inward-serifed"
t = "standard-short-neck"
u = "toothless-rounded-motion-serifed"
v = "curly"
w = "straight"
y = "straight-turn"
z = "curly-serifless"
five = "oblique-upper-left-bar"
seven = "curly-serifed"
lower-lambda = "straight-turn"
punctuation-dot = "round"
diacritic-dot = "round"

[buildPlans.bunniq.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.bunniq.metric-override]
powerlineScaleX = 1
powerlineScaleY = 1

[buildPlans.bunniq.ligations]
inherits = "dlig"
