[buildPlans.bunni]
family = "bunni"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.bunni.variants.design]
capital-z = "curly-serifless"
capital-x = "straight-serifless"
capital-q = "straight"
capital-i = "short-serifed"
capital-f = "top-left-serifed"
capital-c = "unilateral-inward-serifed"
capital-j = "serifless"
capital-b = "standard-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
capital-y = "curly-serifless"
capital-u = "toothed"
capital-n = "asymmetric"
capital-r = "curly"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner"
c = "serifless"
d = "toothed-serifless"
f = "flat-hook"
g = "single-storey-earless-corner-flat-hook"
i = "serifed-flat-tailed"
j = "serifed"
k = "symmetric-connected-serifless"
l = "tailed-serifed"
m = "normal"
# n = "earless-corner-straight"
# p = "earless-corner"
q = "earless-corner"
r = "serifless"
s = "serifless"
t = "standard-short-neck"
# u = "toothless-corner"
u = "toothed"
v = "straight"
x = "straight-serifless"
y = "straight-turn"
z = "curly-serifless"
long-s = "flat-hook"
eszet = "longs-s-lig"
lower-alpha = "tailed-barred"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
lower-xi = "rounded"
cyrl-capital-ka = "straight-serifless"
cyrl-ka = "straight-serifless"
cyrl-capital-u = "straight-turn"
one = "no-base"
two = "curly-neck"
three = "two-arcs"
four = "closed"
five = "vertical-upper-left-bar"
six = "closed-contour"
seven = "straight-serifed"
eight = "crossing"
nine = "closed-contour"
asterisk = "hex-low"
underscore = "low"
pilcrow = "low"
caret = "low"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
ampersand = "closed"
at = "short"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "rings-continuous-slash"
bar = "force-upright"
lig-ltgteq = "slanted"
question = "smooth"
punctuation-dot = "square"
diacritic-dot = "square"

[buildPlans.bunni.variants.italic]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner"
c = "serifless"
d = "toothed-serifless"
e = "rounded"
f = "flat-hook"
g = "double-storey-open"
h = "straight"
i = "tailed-serifed"
j = "serifed"
# k = "diagonal-tailed-cursive-serifless"
l = "tailed"
m = "normal"
# n = "straight"
# q = "earless-corner-diagonal-tailed"
s = "bilateral-inward-serifed"
t = "standard-short-neck"
# u = "toothless-rounded-motion-serifed"
u = "toothed"
v = "straight"
w = "straight"
y = "straight-turn"
z = "curly-serifless"
five = "vertical-upper-left-bar"
seven = "curly-serifed"
lower-lambda = "straight-turn"
punctuation-dot = "square"
diacritic-dot = "square"

[buildPlans.bunni.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.bunni.metric-override]
powerlineScaleX = 1
powerlineScaleY = 1

[buildPlans.bunni.ligations]
inherits = "calt"

[buildPlans.bunnit]
family = "bunnit"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.bunnit.variants.design]
capital-z = "curly-serifless"
capital-x = "straight-serifless"
capital-q = "straight"
capital-i = "short-serifed"
capital-f = "top-left-serifed"
capital-c = "unilateral-inward-serifed"
capital-j = "serifless"
capital-b = "standard-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
capital-y = "curly-serifless"
capital-u = "toothed"
capital-n = "asymmetric"
capital-r = "curly"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner"
c = "serifless"
d = "toothed-serifless"
f = "flat-hook"
g = "single-storey-earless-corner-flat-hook"
i = "serifed-flat-tailed"
j = "serifed"
k = "symmetric-connected-serifless"
l = "tailed-serifed"
m = "normal"
# n = "earless-corner-straight"
# p = "earless-corner"
q = "earless-corner"
r = "serifless"
s = "serifless"
t = "standard-short-neck"
# u = "toothless-corner"
u = "toothed"
v = "straight"
x = "straight-serifless"
y = "straight-turn"
z = "curly-serifless"
long-s = "flat-hook"
eszet = "longs-s-lig"
lower-alpha = "tailed-barred"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
lower-xi = "rounded"
cyrl-capital-ka = "straight-serifless"
cyrl-ka = "straight-serifless"
cyrl-capital-u = "straight-turn"
one = "no-base"
two = "curly-neck"
three = "two-arcs"
four = "closed"
five = "vertical-upper-left-bar"
six = "closed-contour"
seven = "straight-serifed"
eight = "crossing"
nine = "closed-contour"
asterisk = "hex-low"
underscore = "low"
pilcrow = "low"
caret = "low"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
ampersand = "closed"
at = "short"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "rings-continuous-slash"
bar = "force-upright"
lig-ltgteq = "slanted"
question = "smooth"
punctuation-dot = "square"
diacritic-dot = "square"

[buildPlans.bunnit.variants.italic]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner"
c = "serifless"
d = "toothed-serifless"
e = "rounded"
f = "flat-hook"
g = "double-storey-open"
h = "straight"
i = "tailed-serifed"
j = "serifed"
# k = "diagonal-tailed-cursive-serifless"
l = "tailed"
m = "normal"
# n = "straight"
# q = "earless-corner-diagonal-tailed"
s = "bilateral-inward-serifed"
t = "standard-short-neck"
# u = "toothless-rounded-motion-serifed"
u = "toothed"
v = "straight"
w = "straight"
y = "straight-turn"
z = "curly-serifless"
five = "vertical-upper-left-bar"
seven = "curly-serifed"
lower-lambda = "straight-turn"
punctuation-dot = "square"
diacritic-dot = "square"

[buildPlans.bunnit.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.bunnit.metric-override]
powerlineScaleX = 1
powerlineScaleY = 1

[buildPlans.bunnit.ligations]
inherits = "calt"

[buildPlans.bunniq]
family = "bunniq"
spacing = "quasi-proportional-extension-only"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.bunniq.variants.design]
capital-z = "curly-serifless"
capital-x = "straight-serifless"
capital-q = "straight"
capital-i = "short-serifed"
capital-f = "top-left-serifed"
capital-c = "unilateral-inward-serifed"
capital-j = "serifless"
capital-b = "standard-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
capital-y = "curly-serifless"
capital-u = "toothed"
capital-n = "asymmetric"
capital-r = "curly"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner"
c = "serifless"
d = "toothed-serifless"
f = "flat-hook"
g = "single-storey-earless-corner-flat-hook"
i = "serifed-flat-tailed"
j = "serifed"
k = "symmetric-connected-serifless"
l = "tailed-serifed"
m = "normal"
# n = "earless-corner-straight"
# p = "earless-corner"
q = "earless-corner"
r = "serifless"
s = "serifless"
t = "standard-short-neck"
# u = "toothless-corner"
u = "toothed"
v = "straight"
x = "straight-serifless"
y = "straight-turn"
z = "curly-serifless"
long-s = "flat-hook"
eszet = "longs-s-lig"
lower-alpha = "tailed-barred"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
lower-xi = "rounded"
cyrl-capital-ka = "straight-serifless"
cyrl-ka = "straight-serifless"
cyrl-capital-u = "straight-turn"
one = "no-base"
two = "curly-neck"
three = "two-arcs"
four = "closed"
five = "vertical-upper-left-bar"
six = "closed-contour"
seven = "straight-serifed"
eight = "crossing"
nine = "closed-contour"
asterisk = "hex-low"
underscore = "low"
pilcrow = "low"
caret = "low"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
ampersand = "closed"
at = "short"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "rings-continuous-slash"
bar = "force-upright"
lig-ltgteq = "slanted"
question = "smooth"
punctuation-dot = "square"
diacritic-dot = "square"

[buildPlans.bunniq.variants.italic]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner"
c = "serifless"
d = "toothed-serifless"
e = "rounded"
f = "flat-hook"
g = "double-storey-open"
h = "straight"
i = "tailed-serifed"
j = "serifed"
# k = "diagonal-tailed-cursive-serifless"
l = "tailed"
m = "normal"
# n = "straight"
# q = "earless-corner-diagonal-tailed"
s = "bilateral-inward-serifed"
t = "standard-short-neck"
# u = "toothless-rounded-motion-serifed"
u = "toothed"
v = "straight"
w = "straight"
y = "straight-turn"
z = "curly-serifless"
five = "vertical-upper-left-bar"
seven = "curly-serifed"
lower-lambda = "straight-turn"
punctuation-dot = "square"
diacritic-dot = "square"

[buildPlans.bunniq.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.bunniq.metric-override]
powerlineScaleX = 1
powerlineScaleY = 1

[buildPlans.bunniq.ligations]
inherits = "calt"
