name: "Task"
description: Create a tasklist.
title: "[TASK] - <title>"
labels: []
body:
  - type: textarea
    id: tasklist
    attributes:
      label: "Tasks"
      description: Please enter the tasks here.
      placeholder: "- [] task"
    validations:
      required: true
  - type: markdown
    id: check
    attributes:
      value: If this edits the look of the font, add the "font change" label.
